#!/bin/bash
pandoc --highlight-style=tango \
       --toc \
       --latex-engine=pdflatex \
       -V fontsize=12pt \
       -V documentclass:book \
       -V papersize:a4paper \
       -V classoption:openright \
       -V classoption:oneside \
       --chapters \
       --bibliography=papers.bib \
       --csl="csl/ieee-with-url.csl" \
       *-*.md \
       -c "css/github-pandoc.css" \
       -o "thesis.html"
